# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\",\n\x0eMessageRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"%\n\x07Message\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\".\n\x0bMessageList\x12\x1f\n\x08messages\x18\x01 \x03(\x0b\x32\r.chat.Message2o\n\x0b\x43hatHistory\x12\x30\n\x0bSaveMessage\x12\x14.chat.MessageRequest\x1a\x0b.chat.Empty\x12.\n\x0cListMessages\x12\x0b.chat.Empty\x1a\x11.chat.MessageListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=20
  _globals['_MESSAGEREQUEST']._serialized_end=64
  _globals['_EMPTY']._serialized_start=66
  _globals['_EMPTY']._serialized_end=73
  _globals['_MESSAGE']._serialized_start=75
  _globals['_MESSAGE']._serialized_end=112
  _globals['_MESSAGELIST']._serialized_start=114
  _globals['_MESSAGELIST']._serialized_end=160
  _globals['_CHATHISTORY']._serialized_start=162
  _globals['_CHATHISTORY']._serialized_end=273
# @@protoc_insertion_point(module_scope)
